Basic Login Page
KamandPrompt/SAC-Portal pull request #9
Opened 2020-03-25 12:45 UTC by naveensaigit

I have designed a basic login page which redirects to basic.html if email ends with @students.iitmandi.ac.in and has a valid roll no.

2020-03-25 14:29 UTC, Milind712000 requested changes
opening the app gives an error as basic.html is not in the templates folder
- [x] Rename basic.html and all its references to index.html and move it to templates folder
- [x] Aslo seperate your css and put it in a different file
- [x] Create a layout.html and extract the commonly repeated html to it (make use of Jinja2)
- [ ] the flash message "You have logged-in successfully" cannot be seen currently
- [ ] You used a dependency called wtfforms add the dependency to requirements.txt

2020-03-25 14:29 UTC, Milind712000 commented on templates/login.html
> +        color:color:rgb(139, 143, 140);
invalid css

2020-03-25 14:38 UTC, Milind712000 commented
I'll have requirements.txt made and commited in a different PR
till then focus on fixing the other issues

2020-03-26 09:24 UTC, naveensaigit commented
I have renamed basic.html to index.html. 
I have created a layout.html. 
I did separate the css, but using an external stylesheet is not working in my system. Please take a look at this.
Lastly, I am unable to figure out why the flash message is not working. Please take a look at this too

2020-03-26 11:21 UTC, naveensaigit commented
I have updated everything.
CSS works fine.
The flash message is now displayed correctly for successful as well as unsuccessful login.

2020-03-26 15:35 UTC, closed without merging